version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
  catamel:
    build:
      context: .
      dockerfile: CI/ESS/Dockerfile.test
    image: garethcmurphy/catamel
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - openldap-seed
    links:
      - mongodb
      - openldap
      - openldap-seed
  openldap:
      image: osixia/openldap
      container_name: openldap
      hostname: openldap
      environment:
          LDAP_ORGANISATION: "LDAP Catamel Auth"
          LDAP_SSL_HELPER_PREFIX: "ldap"
          LDAP_TLS_VERIFY_CLIENT: "never"
          LDAP_LOG_LEVEL: 256
          LDAP_ADMIN_PASSWORD: "admin"
      ports:CI/ESS/envfiles/settings.sample.json
      - "389:389"
  openldap-seed:
      image: osixia/openldap
      volumes:
      - ./CI/ESS/ldif_files:/ldif_files
      links:
      - openldap
      entrypoint: sh -c '/ldif_files/addAll.sh'
  openldap-admin:
      image: osixia/phpldapadmin
      container_name: openldap-admin
      hostname: openldap-admin
      environment:
          PHPLDAPADMIN_HTTPS=false:
          PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      ports:
      - "8080:80"
      links:
      - "openldap:openldap"
      depends_on:
      - openldap
volumes:
    mongodb_data:
        driver: local
